#soluppgång-----------
  - alias: 'Soluppgång'
    trigger:
      platform: sun
      event: sunrise
      offset: '+00:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.Entre_Ute
      - delay: 00:00:05
      - service: light.turn_off
        entity_id:
          - light.altantak
          - light.garage_baksida
          - light.garage_framsida
          - light.garageuppfart
      - service: persistent_notification.create
        data:
         message: "Entre Ute {{ states('switch.Entre_Ute') }}"
         title: "Entre Ute"
         notification_id: "1111"
      - service: notify.pushbullet
        data:
          message: "Entre Ute {{ states('switch.Entre_Ute') }}"
          title: "Entre Ute"
#solnedgång---------------------------------------------
  - alias: 'Solnedgång'
    trigger:
      platform: sun
      event: sunset
      offset: '-00:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.Entre_Ute
      - delay: 00:00:05
      - service: light.turn_on
        entity_id:
          - light.altantak
          - light.garage_baksida
          - light.garage_framsida
        data:
         brightness_pct: 25
      - service: persistent_notification.create
        data:
         message: "Entre Ute {{ states('switch.Entre_Ute') }}"
         title: "Entre Ute"
         notification_id: "1111"
      - service: notify.pushbullet
        data:
          message: "Entre Ute {{ states('switch.Entre_Ute') }}"
          title: "Entre Ute"
# Fontän AV------------------------------------
  - alias: 'Stänger av fontänen'
    trigger:
      platform: time
      at: '23:30:00'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.Fontan
      - delay: 00:00:05
      - service: persistent_notification.create
        data:
         message: "Fontän {{ states('switch.Fontan') }}"
         title: "Fontän"
         notification_id: "1111"
      - service: notify.pushbullet
        data:
          message: "Fontän {{ states('switch.Fontan') }}"
          title: "Fontän"
# Fontän på-------------------------------------
  - alias: 'Startar av fontänen'
    trigger:
      platform: time
      at: '06:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.Fontan
      - delay: 00:00:05
      - service: persistent_notification.create
        data:
         message: "Fontän {{ states('switch.Fontan') }}"
         title: "Fontän"
         notification_id: "1111"
      - service: notify.pushbullet
        data:
          message: "Fontän {{ states('switch.Fontan') }}"
          title: "Fontän"

# HASS----
  - alias: "Notify Larm"
    trigger:
      platform: state
      entity_id: alarm_control_panel.duvesjon_374
    action:
      - service: notify.pushbullet
        data:
          message: "Larmet är {{ states('alarm_control_panel.duvesjon_374') }}"
          title: "Larm"
#Johan
  - alias: "Hemma johan"
    trigger:
      platform: state
      entity_id: device_tracker.homeassistant_johan
    action:
      - service: notify.pushbullet
        data:
          message: "Johan {{ states('device_tracker.homeassistant_johan') }}"
          title: "Hemma"
#Cicci
  - alias: "Hemma cicci"
    trigger:
      platform: state
      entity_id: device_tracker.homeassistant_cicci
    action:
      - service: notify.pushbullet
        data:
          message: "Cicci {{ states('device_tracker.homeassistant_cicci') }}"
          title: "Hemma"
#Update CHECK
  - alias: "Update Available Notification"
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      - service: notify.pushbullet
        data:
          message: "HomeAssistant {{ states('updater.updater') }} is now available"
          title: "Update HASS"
      - service: persistent_notification.create
        data:
         message: "HomeAssistant {{ states('updater.updater') }} är nu tillgänglig"
         title: "HomeAssistant"
         notification_id: "2222"

  - alias: 'Sonos Say'
    trigger:
     platform: state
     entity_id: alarm_control_panel.duvesjon_374
    action:
     - service: script.sonos_say
       data:
         sonos_entity: media_player.kok
         volume: 0.4
         message: 'Välkommen hem'

  - alias: "Sonos Play ON"
    trigger:
     platform: state
     entity_id: switch.Sonos_altan_play
     from: "off"
     to: "on"
    action:
       - service: media_player.media_play
         entity_id: media_player.tradgard

  - alias: "Sonos Play OFF"
    trigger:
     platform: state
     entity_id: switch.Sonos_altan_play
     from: "on"
     to: "off"
    action:
       - service: media_player.media_pause
         entity_id: media_player.tradgard

  - alias: "Sonos Status playing"
    trigger:
     platform: state
     entity_id: media_player.tradgard
     to: "playing"
    action:
       - service: homeassistant.turn_on
         entity_id: switch.Sonos_altan_status

  - alias: "Sonos Status paused"
    trigger:
     platform: state
     entity_id: media_player.tradgard
     to: "paused"
    action:
       - service: homeassistant.turn_off
         entity_id: switch.Sonos_altan_status


  - alias: Sonos max buss
    trigger:
      platform: time
      at: '07:45:00'
    action:
     - service: script.sonos_say
       data:
         sonos_entity: media_player.kok
         volume: 0.3
         message: 'Max måste gå till bussen om 10 minuter'


#  - alias: "auto larm on"
#    trigger:
#       platform: state
#       entity_id: group.family_info
#       state: "not_home"
#    condition:
#     condition: and
#     conditions:
#     - condition: state
#       entity_id: "sensor.template_last_motion"
#       state: "Entre"
#       for:
#         minutes: 10
#     - condition: state
#       entity_id: "alarm_control_panel.duvesjon_374"
#       state: "disarmed"
#     action:
#       - service: notify.pushbullet
#         data:
#           message: "Larmet aktiveras om 10minuter"
#           title: "Larm"
#       - delay: 00:10:00
#       - service: notify.pushbullet
#         data:
#           message: "Larmet aktiverat"
#           title: "Larm"
